### ISSUE TITLE
Create a Project

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#32]
As a User, I want to create a project to start collecting funds.  

You can find he design here: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=1908%3A68916 - Create a project

This is the Design System guides: https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=13%3A4

Pls note, before the user get started, we have this modal for the first time: (find it under Modals section) 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/353007a0-527a-4517-b882-e1d5108c8c43)

**Comment by MoeNick** [comment]
@mohammadranjbarz would u pls link the new services for preview (draft) service ?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz would u pls link the new services for preview (draft) service ?

https://github.com/Giveth/impact-graph/issues/361#issuecomment-1046499792

@RamRamez  please ask me if you had any qestion

**Comment by MoeNick** [comment]
**QA issues:**

- [x] 1- ON EDIT, FOR NOT PICTURE, LOAD UPLOAD
- [x] 2- Cherik component on picture loading - especially deleting pictures
- [x] 3- Remove errors of empty fields on the bottom of the page.
- [x] 4- Styling: submit / pressed , hover ... (text boxes and below buttons) 
- [x] 5- Informative Modal should be based on design, removing Got IT . 
- [x] after closing move the title of modal beside the page.
- [x] 6- remove the modal on edit.
- [x] 7- Improvement, separate upload from publishing.
- [x] 8- Disabled recipient address when the address is correct and show change address. 
- [x] 9- Change error colors to red
- [x] 10- Fix success view project card
- [x] 11- Redirect to success view after publish in create view and single project view

**Comment by RamRamez** [comment]
Related to this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/118)
