### ISSUE TITLE
TP: Reward Menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#34]
As a user, I want to see the numbers below GIV button in the header like this:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/f9334966-e32c-46f4-8766-b1ca04e14e2e)

The design with responsiveness guides are available here: https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=13%3A4

It will load on hover in desktop view and tap in mobile view.

**Comment by RamRamez** [comment]
PR #59

1. transfer new header features from next version to typescript
2. some improvements on responsiveness
3. sign-in sign-out is still WIP
