### ISSUE TITLE
TP: Footer

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#35]
- [x] All of Social links are broken.
- [x] Link if Support us with your Donation - revolution.eth is broken

**Comment by pkretzschmar** [comment]
Hey @MoeNick! Could you send me the donate link? Thanks!

**Comment by MoeNick** [comment]
@pkretzschmar Hi. Happy to have you here. Here you are:{test or live env}/donate/the-giveth-community-of-makers

Pls note whenever you find broken links it should be like what we have on giveth.io

**Comment by pkretzschmar** [comment]
@MoeNick hey Moe, I fix the donate link! But after the redirect, it seems that the page doesn't exist.

**Comment by MoeNick** [comment]
@pkretzschmar I couldn't test it on typescript.giveth.io, I think the PR is still open and did not merge.

**Comment by MoeNick** [comment]
Move it back to inprogress
