### ISSUE TITLE
Partner page needs to be finalized  and links need to get updated

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#38]

**Comment by MoeNick** [comment]
@divine-comedian @laurenluz can you guys help me find out right content for it?

**Comment by MoeNick** [comment]
@pkretzschmar we decided to moe to scrum, So appreciate if you can provide estimations, so I can have a clue on managing issues and planning the milestones
Thanks

**Comment by divine-comedian** [comment]
>  can you guys help me find out right content for it?

all of this info is stored in contentful right now, is that what you're asking?

**Comment by MoeNick** [comment]
@MohammadPCh 
@pkretzschmar did this page move to V2 version? I can't see it in V2 cause the footer links are broken:
https://typescript.giveth.io/partnerships

**Comment by pkretzschmar** [comment]
@MoeNick just checked here, it's not updated with my last changes.
