### ISSUE TITLE
User Profile public page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#41]
As a user, I want to see other PMs or other users' data, I need to see their projects, donations, and also liked projects. 

# Design resources

- [Public profile | Projects tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3863%3A103757)

- [Public profile | Donations](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3867%3A104720)

- [Public profile | Liked projects](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3869%3A105648)

_Note: Donations table style might slightly be changed, but other than that it's all there._

---

Backend needed services:

- [x] Get Donations, Sorting by Date 
- [x] Get Donations, sorting by Token Amount
- [x] Get Donations, sorting by USD Amount
- [x] Pagination
- [x] Auto-Test Included  ( [the issue ](https://github.com/Giveth/impact-graph/issues/332) )
@mohammadranjbarz  (3 out of 13 is for back-end changes)

**Comment by mosaeedi** [comment]
I'm going to add the designs asap!

**Comment by MoeNick** [comment]
@mosaeedi pls provide links

**Comment by markoprljic** [comment]
@MoeNick https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3863%3A103757
Donations table might slightly be adjusted the style, but other than that it's all there.

**Comment by MoeNick** [comment]
@CarlosQ96 According to Mohammad the backend of sorting donations with pagination is included in this Story.
Sorting should be on Amount, UDS Amount and date, both ascending / descending. (Auto test is also included)

**Comment by mohammadranjbarz** [comment]
@MohammadPCh 

The backend side is implemented by @CarlosQ96  and is on staging, 
you can use this query to get donations of a user:

```
  query{
    donationsByUserId(
      take: 10
      skip: 0
      orderBy:{
        #   field: TokenAmount
        #   field: CreationDate
          field: UsdAmount
          direction :DESC
      }
      userId: 117
    ) {
      donations {
        id
        transactionId
        transactionNetworkId
        toWalletAddress
        fromWalletAddress
        currency
        anonymous
        valueUsd
        amount
        user {
          id
        }
        project {
          id
        }
        createdAt
      }
      totalCount
    }
  }
```

https://github.com/Giveth/impact-graph/pull/352#issuecomment-1032253933

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  And @CarlosQ96 implemented 

```
query {
  likedProjectsByUserId(take: 1, skip: 0, userId: 255) {
    projects {
      id
      title
    }
    totalCount
  }
}
```
https://github.com/Giveth/impact-graph/pull/352#issuecomment-1032253035
as well

**Comment by MohammadPCh** [comment]
Thanks guys @CarlosQ96 @mohammadranjbarz
