### ISSUE TITLE
Search Box Problems - Styles (also clear box) and No results found. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#46]
UX UI problems which is not implemented yet. 

- [x] According to designSystem: https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=13%3A4
Under components section. Search result and clear search box should follow the design:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/bde793c3-0097-4226-919c-9fdab6fed5b8)

- [x]  If "No results found:. Try again OR Back (clear search box) it needs a design 
Designed here: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4016%3A111401

**Comment by MoeNick** [comment]
@markoprljic the no result design is needed here I think.

**Comment by RamRamez** [comment]
[This search box](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=1908%3A67157) doesn't have the left arrow but [here ](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=13%3A4) it has.
Which one should be implemented and what's the function of the arrow?

**Comment by RamRamez** [comment]
Resolved in PR [#11](https://github.com/Giveth/giveth-dapps-v2/pull/11) in V2 repo

**Comment by MoeNick** [comment]
It has a bug when clicking on back.

**Comment by MoeNick** [comment]
Pressed is not following design system, also no result appears in left of the screen. 
there is a tiny bug which I can't get back to main page when I click on <- button.

**Comment by RamRamez** [comment]
Done in PR [#40](https://github.com/Giveth/giveth-dapps-v2/pull/40)
