### ISSUE TITLE
Our Team Page needs to get updated

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#50]
https://giveth-dapps-v2.vercel.app/about

**Comment by MoeNick** [comment]
@divine-comedian It needs some QAing and newer content if available, Appreciate if you can leave your comments here.

**Comment by divine-comedian** [comment]
I made a fresh call for team member updates and have been updating them in my local branch

**Comment by MoeNick** [comment]
@divine-comedian I can test it here https://giveth-dapps-v2.vercel.app/about
Can you have a PR and make the edits to team tab?

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-io-typescript/50?planning-poker) with ZenHub @divine-comedian @RamRamez

**Comment by pkretzschmar** [comment]
@MoeNick I was taking a look on the page, and there is some content missing (a lot of _Lorem ipsum_ stuff there). Also, it would be nice to know the team members that are missing right now!

**Comment by MoeNick** [comment]
> @MoeNick I was taking a look on the page, and there is some content missing (a lot of _Lorem ipsum_ stuff there). Also, it would be nice to know the team members that are missing right now!

@pkretzschmar 

for **About us Tab**, pls have this text: 

Giveth is a community focused on Building the Future of Giving using blockchain technology. Our intention is to support and reward the funding of public goods by creating open, transparent and free access to the revolutionary funding opportunities available within the Ethereum ecosystem. 

Giveth is building a culture of giving that empowers and rewards those who give -- to projects, to society, and to the world. We aim to inspire our community to participate in an ecosystem of collective support, abundance and value-creation.
Check out our [Calendar](https://calendar.google.com/calendar/u/1?cid=Z2l2ZXRoZG90aW9AZ21haWwuY29t) and [Join Page](https://giveth.io/join) to get more involved.


I make another issue for **history tab** and the content is provided there: https://github.com/Giveth/giveth-io-typescript/issues/51


for **Team members**, you can copy from https://giveth.io/about @divine-comedian will update and QA us afterward, no worries

Thanks

**Comment by divine-comedian** [comment]
I began updating the team page on the typescript version based on the info in our contentful you can find it on 
https://github.com/Giveth/giveth-io-typescript/tree/mitch-text-1

there's some updates in the commit in there on the about page which I think is no longer relevant however the team page content is good.
