### ISSUE TITLE
Implement Modals: insufficient fund

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#54]
You can find the design here under Modal section:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3515%3A96868

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/1857253a-e7bf-4c82-a801-a85d1b841c8c)

**Comment by aminlatifi** [comment]
Needs some components first implemented in design-system. Specifically modal header

**Comment by MoeNick** [comment]
I cant see the PR, is it testable right now? would u pls move it in the pipeline @aminlatifi

**Comment by aminlatifi** [comment]
@MoeNick No, I have prepared the icons and modal headers in design system

**Comment by MoeNick** [comment]
@mateodaza fyi integration with Donation Page
