### ISSUE TITLE
Get rid of contentful

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-io-typescript#56]
Right now we use contentful for the FAQ & team pages. Maybe others? @WhyldWanderer @divine-comedian would know

The comms team would love to get rid of contentful and just be able to update the content in the code instead.

This should also improve the efficiency of the DApp!

**Comment by RamRamez** [comment]
@laurenluz In typescript version the contentful is completely removed. All the content is on `/src/content`

**Comment by MoeNick** [comment]
just fyi or you can test and say if it has a problem, 
@divine-comedian @mateodaza

**Comment by laurenluz** [comment]
oh NICE

**Comment by divine-comedian** [comment]
amazing!!
