### ISSUE TITLE
SortBy: My Favorites ? ideas? 

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-io-typescript#57]
**What new feature(s) would you like to see on Giveth?**
Hi, I gave some projects I like a heart with the idea I could easily come back to them later to donate. I thought of it like a bookmark. But when I sort by hearts it shows projects with the most hearts. That is nice too, but would it be possible to add something like sorting by "My hearts" that would show the projects that I gave a heart? That would help me follow projects I am considering to donate to.

**Comment by MoeNick** [comment]
@markoprljic we can easily add sort-by "my favorites" in sort-by drop-done menu. 
What do you think?

**Comment by CarlosQ96** [comment]
I actually kind of like this idea. Would query by projects the person gave a heart reaction to, not complicated to do. @MoeNick

**Comment by markoprljic** [comment]
> @markoprljic we can easily add sort-by "my favorites" in sort-by drop-done menu. What do you think?

Yes, adding a sort filter is one thing we can add right away. 
Also, in My Account there should be a list of all "Liked" projects.
