### ISSUE TITLE
Deactivate (Archive) Projects 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#61]
As a Project Manager (PM) I want to archive my project so that I can stop receiving donations.

Acceptance criteria:

Given the PM wants to take down their project, When they can click on the button to archive it (if signed In) 

>  {pls consider now PM can see this button only after clicking in Edit Project. } 

Then:
- the system should warn PM to confirm this action. 
- PM should provide a good reason of doing this (preferably to select from a list of common reasons)
- PM should be informed that all donors (who have email address) will be notified about this action
- PM will be encouraged and offered to donate the funds received for this project to another project on Giveth
- project will be unlisted from the platform. 
- PM will see his project under Archived section in their Account

>  { I suggest we don't add archived section, so PM can see the archived Projects in "My Projects" with only a tag.}

- Users still can see the project if they have direct url, with a notification on the top : "This project is archived and no longer accepts donations  -> a link to docs to describe what is Archived Projects. 
- If it's Traceable, we change the related Campaign to archived. 

PM can unarchive the project himself, in this case, he see a unarchive button for archived projects. 
Same as above:
*  the system should warn PM to confirm this action. 
*  PM should be informed that all donors (who have email address) will be notified about this action
* project will be set to not reviewed from the platform. 
* If it's Traceable, we change the related Campaign to active.
---

# Design Resources
_Please check the link for design resources on Figma_

Deactivating a project: [Starts from here!](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4107%3A210665)

**Deactivating modals:**
- [More about deactivating](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3879%3A106127)
- [Reasons for deactivating](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3879%3A106350)
- [deactivated](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3881%3A104874)

After a project is deactivated->
 [Deactivated Project | Owner view](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4103%3A108703)
[Deactivated Project | Public view](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4116%3A109182)

---

**Comment by MoeNick** [comment]
@mosaeedi after archiving design needed

**Comment by mosaeedi** [comment]
@MoeNick Design resources added.

**Comment by mosaeedi** [comment]
@MoeNick, it's updated.

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-io-typescript/61?planning-poker) with ZenHub @pkretzschmar

**Comment by MoeNick** [comment]
**Testing on https://giveth-dapps-v2.vercel.app/project/acc1-active-project** @pkretzschmar 

After I click on deactivating, it asks me for sign my wallet, and after I sign, nothing happens. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4fdc396e-4d5e-4376-b50f-d3b8aaa835f4)
