### ISSUE TITLE
Edit Profile Modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#62]
As user, I may need to edit my profile items, like Name, Email, Location or picture. 

# Design resources

- [Edit profile | Empty form](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3922%3A106144)

- [Edit profile | Filled form](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3977%3A143531)

---

- [Edit profile | Upload photo](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3923%3A106471)

- [Edit profile |Photo uploading](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3923%3A107080)

- [Edit profile |Photo uploaded](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3926%3A107285)

---

**Comment by mosaeedi** [comment]
I'm going to add the designs asap!

**Comment by MoeNick** [comment]
I have to add my comments here.

**Comment by MoeNick** [comment]
@mosaeedi appreciate if you can provide links and make it tidy as well.

**Comment by markoprljic** [comment]
@MoeNick https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3922%3A105825
