### ISSUE TITLE
MyAccount Overview

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#69]
[Over View Page Design](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3889%3A104687)

Elements:

- [ ] Short Profile Description
- [ ] Donations total amount / total count - Amount should be calculated based on the USD value of currant 
- [ ] Total projects

**Comment by mateodaza** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #43](https://github.com/Giveth/giveth-dapps-v2/issues/43) via [**ZenHub**](https://www.zenhub.com/)
