### ISSUE TITLE
My Account | Donations

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#70]
As us user I want to see list my donations and the USD value of them. 

# Design resources

- [My donations tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4393%3A112100)

Note: for the current state we only have the sorting on the table, we'll add filtering in the next sprints.

**Comment by mateodaza** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #44](https://github.com/Giveth/giveth-dapps-v2/issues/44) via [**ZenHub**](https://www.zenhub.com/)
