### ISSUE TITLE
My Account | Projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#71]
As a Project Owner, I would love to see all of my donations and their status on a list. 

# Design resources

- [My projects tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3898%3A104982)

_Note: for the current state, we only have the sorting on the table, we will add the Filters in the next sprint_

**Comment by mateodaza** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #45](https://github.com/Giveth/giveth-dapps-v2/issues/45) via [**ZenHub**](https://www.zenhub.com/)
