### ISSUE TITLE
My Account | Liked Projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#72]
Me as user, want to see my liked projects in a list, so I can take a look at them later. 

# Design resources
- [Liked projects tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3898%3A119902)
---

**Comment by mateodaza** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #46](https://github.com/Giveth/giveth-dapps-v2/issues/46) via [**ZenHub**](https://www.zenhub.com/)
