### ISSUE TITLE
Warn user when donating with not-whitelisted GIVbacks token

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#81]
@markoprljic the GIVbacks token list is the same as our drop-down list of tokens (right? @mateodaza @mohammadranjbarz) so the tokens that won't be eligible are ones that user copy/pastes in the address for. I don't think we need to have the "all" and "GIVbacks eligible" selectors.

I do think we should keep the message "This Token is/is not eligible for GIVbacks Learn more"

I also totally understand that we don't want to send the user away from the donation page... but we should someone make it easy/possible for the to navigate from a page referring to the token list... to [the token list itself](https://forum.giveth.io/t/givbacks-token-list/253)... then if they want to request a token to be added to the list, they can do so.

I can write copy for the modal, but waiting on your feedback.

_Originally posted by @laurenluz in https://github.com/Giveth/giveth-next/issues/606#issuecomment-1014825041_

**Comment by markoprljic** [comment]
https://github.com/Giveth/giveth-next/issues/606#issuecomment-1011028740
