### ISSUE TITLE
In Brave: Add popup for torus login users telling them to lower shields

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-io-typescript#83]
As a Brave user, when I need to use Torus, I need to have the warning to turn of my shield and let the cookies on in the setting, so I can be able to use Torus on Brave.

---

# Design resources

- [Lower shield modal](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4401%3A113332)
---

**Comment by laurenluz** [comment]
sounds great! take it away :)

**Comment by laurenluz** [comment]
The issue is basically that torus users will run into issues (things just won't work as expected) unless they "lower shields" on brave (maybe other browsers too?). There is an issue to add this to the documentation in comms: https://github.com/Giveth/giveth-planning/issues/451

The idea is that when a user tries to login with torus, they get a popup that tells them something like "Please lower shields on your browser in order to use Giveth with your Torus wallet. Read more." And read more links to the docs.

@mateodaza can you confirm? does this make sense?

**Comment by mateodaza** [comment]
> The issue is basically that torus users will run into issues (things just won't work as expected) unless they "lower shields" on brave (maybe other browsers too?). There is an issue to add this to the documentation in comms: [Giveth/giveth-planning#451](https://github.com/Giveth/giveth-planning/issues/451)
> 
> The idea is that when a user tries to login with torus, they get a popup that tells them something like "Please lower shields on your browser in order to use Giveth with your Torus wallet. Read more." And read more links to the docs.
> 
> @mateodaza can you confirm? does this make sense?

Yes exactly, but only for Brave browser. It is also recommended to allow cookies. I've noticed that the shield is not enough sometimes

**Comment by laurenluz** [comment]
Is there some easy way from a dev standpoint to know if the user is on Brave then? because perhaps the popup won't make any sense if they are on chrome, for example.  @mateodaza

**Comment by mateodaza** [comment]
Yeah, that's totally possible. We can make that condition to only be seen on Brave browsers @laurenluz

**Comment by laurenluz** [comment]
ok @markoprljic so what we need is... if the user is on brave browers, and they select torus wallet they get a popup that says:

"Please lower shields on your browser in order to use Giveth with your Torus Wallet. Learn more."

And learn more connects to our issue in: Giveth/giveth-planning#451

**Comment by markoprljic** [comment]
@mosaeedi Please update the Modals component so that devs have a reusable component to choose from for this and similar use cases https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=1327%3A55799

@laurenluz @MoeNick As soon as the Modal component is done devs can implement this and close the issue.

**Comment by RamRamez** [comment]
@markoprljic @mosaeedi Shall I use this modal for dark theme too? Or we have another design for it?

**Comment by mosaeedi** [comment]
@RamRamez 
The modal for the Dark theme is also added, please take a look.

Shortcut: [Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=6531%3A137842)
