### ISSUE TITLE
Backend: Provide Reasons to deactivating the projects. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#84]
As an Admin, I need to know the reasons for deactivating the projects by the user. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/57cb9f49-3936-4d23-b2e3-b5946232779d)

The values are :
- The project has completed its goals!
- The project is no longer in need of funding.
- The project is no longer active.
- The project was made by mistake.
- Other / Prefer not to say.

Success Criteria:
The latest status reason for deactivating a project should save by a back-end service with a changing date. Testing of the service is fine enough. no front-end effort is needed. 
(Suggested: this status reasons may apply for other changing statuses in the future, for example from active to canceled by admin. )

**Comment by laurenluz** [comment]
- The project has completed its goals!
- The project is no longer in need of funding.
- The project is not longer active.
- The project was made by mistake.
- Other / prefer not to say.

@WhyldWanderer - what do you think?

**Comment by WhyldWanderer** [comment]
I think those are great!!... 
I think we used the term deactivate before but this will be essentially the same action right?

**Comment by MoeNick** [comment]
> I think those are great!!... I think we used the term deactivate before but this will be essentially the same action right?

Yes. But what you prefer? "active - diactive" terminology? 
And we have canceled which is happening by the admin, it's another else.

**Comment by WhyldWanderer** [comment]
I think 'deactive' is a fine term... I just wanted to make sure I correctly understood the function behind it

I cant think of any other reasons than the ones Lauren already suggested.

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-io-typescript/84?planning-poker) with ZenHub @mohammadranjbarz @CarlosQ96

**Comment by CarlosQ96** [comment]
For some reason I can't add an estimate so i'll go with 5 points.

**Comment by mohammadranjbarz** [comment]
@pkretzschmar 

Hey Pedro
For this issue
I added a new query in backend ( it's still in code review https://github.com/Giveth/impact-graph/pull/353, but I give you the spec, so you can start implementing)

```
query {
    getStatusReasons(statusId: 6) {
                    id
                    description
                    status {
                        id
                        name
                    }
    }
}
```

Response is like this:
```
{
    "data": {
        "getStatusReasons": [
            {
                "id": "1",
                "description": "The project has completed its goals!",
                "status": {
                    "id": "6",
                    "name": "cancelled"
                }
            },
            {
                "id": "2",
                "description": "The project is no longer in need of funding.",
                "status": {
                    "id": "6",
                    "name": "cancelled"
                }
            },
            {
                "id": "3",
                "description": "The project is not longer active.",
                "status": {
                    "id": "6",
                    "name": "cancelled"
                }
            },
            {
                "id": "4",
                "description": "The project was made by mistake.",
                "status": {
                    "id": "6",
                    "name": "cancelled"
                }
            },
            {
                "id": "5",
                "description": "Other / prefer not to say.",
                "status": {
                    "id": "6",
                    "name": "cancelled"
                }
            }
        ]
    }
}
```

So we have some reasons for some statuses, when user wants to deactivate the project, you get the reasons and show the reasons with `status.id:6`
and then for deactivating you can add a **reasonId** , but this is optional, if you don't send it, it would be ok

mutation:
```
  mutation ($projectId: Float!, $reasonId: Float) {
    deactivateProject(projectId: $projectId, reasonId: $reasonId)
  }
  ```

**Comment by mohammadranjbarz** [comment]
@MoeNick  It's ready now, you can activate/deactivate your project and see the history record for them in admin bro, When front is ready the client can send reasonId as well,  we can (I suggest) create another issue to create record when status change happens by admin ( from admin bro panel)

![Screen Shot 1400-11-20 at 10.26.37.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/8db2e7df-f759-4d26-94d8-ee795fc856d0)

**Comment by mohammadranjbarz** [comment]
@pkretzschmar  The changes that I mentioned before is on staging now

**Comment by MoeNick** [comment]
@pkretzschmar can you approve the backednd?
