### ISSUE TITLE
Activate (Unarchive) project

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-io-typescript#85]
As a Project Manager, want to activate my deactiveated project again, so I can be able to recieve funds. 

When a project is archived, the owner can unarchive the project, but the project will be unlisted and they had to go through the verification process again.

### Design resource

Start from here -> [project side card](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4116%3A108693)

Unarchiving modals -> 
[Confirmation](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4116%3A108893)
[Success](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4116%3A109428)

## Success Criteria
1. Make a project deactivated. 
2. User goes to the process above and try to activate his project
3. Project should be now active in admin bro and changes in UI shows it's active now.

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-io-typescript/85?planning-poker) with ZenHub @mateodaza @MohammadPCh @pkretzschmar @RamRamez
