### ISSUE TITLE
Give heart optimization

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-io-typescript#88]

**Comment by mosaeedi** [comment]
Number's not visible on white backgrounds

**Comment by mosaeedi** [comment]
![Screen Shot 2022-02-22 at 2.55.49 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fa6ea0c4-d8a7-49cb-a855-aaa3f82a2b6d)

The structure changed, so user can see like and share button all the time,
the color changed and added a drop shadow to make it visible on all background colors.

**Comment by mosaeedi** [comment]
@markoprljic  @MoeNick

**Comment by markoprljic** [comment]
Great! Thanks @mosaeedi

**Comment by MoeNick** [comment]
Alteady implemented
