### ISSUE TITLE
Update partnerships page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-io-typescript#92]
there's been quite a few changes to our partnerships - this is a reminder to update our partnerships on the page to reflect what is currently on https://giveth.io/partnerships 

content for this page can all be found on contentful.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/d0176168-98cd-44ec-b1ac-093e5fda3d15)

**Comment by pkretzschmar** [comment]
Hey, I update the partner's page when I fixed the URL's on Giveth/giveth-dapps-v2#59
